#pragma config(Sensor, S3,     colorPort,      sensorCOLORFULL)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 335;
task main()
{
	while(1){
		short nAtoDValues[4];
		getColorSensorData(colorPort, colorAtoD,   &nAtoDValues[0]);
		int value;
		value = (nAtoDValues[0]+nAtoDValues[1]+nAtoDValues[2]+nAtoDValues[3])/3;
		nxtDisplayCenteredTextLine(4, "%i", value);
		bool done = false;
		int x;
		while(value > threshold){
			motor[motorB] = 100;
			motor[motorC] = 100;
			nxtDisplayCenteredTextLine(4, "%i", value);
			getColorSensorData(colorPort, colorAtoD,   &nAtoDValues[0]);
			value = (nAtoDValues[0]+nAtoDValues[1]+nAtoDValues[2]+nAtoDValues[3])/3;
			wait1Msec(5);
		}
		while(value < threshold){
			getColorSensorData(colorPort, colorAtoD,   &nAtoDValues[0]);
			value = (nAtoDValues[0]+nAtoDValues[1]+nAtoDValues[2]+nAtoDValues[3])/3;
			for(x=1; x < 121; x=x+1){
				if(value < threshold){
					motor[motorB] = 100;
					motor[motorC] = -100;
					wait1Msec(5);
					nxtDisplayCenteredTextLine(4, "%i", value);
				}else{
					done=true;
					break;
				}
			}
			motor[motorB] = -100;
			motor[motorC] = 100;
			wait1Msec(600);
			getColorSensorData(colorPort, colorAtoD,   &nAtoDValues[0]);
			value = (nAtoDValues[0]+nAtoDValues[1]+nAtoDValues[2]+nAtoDValues[3])/3;
			if(done == false){
				for(x=1; x < 121; x=x+1){
					if(value < threshold){
						motor[motorB] = -100;
						motor[motorC] = 100;
						getColorSensorData(colorPort, colorAtoD,   &nAtoDValues[0]);
						int value;
						value = (nAtoDValues[0]+nAtoDValues[1]+nAtoDValues[2]+nAtoDValues[3])/3;
						nxtDisplayCenteredTextLine(4, "%i", value);
						wait1Msec(5);
					}else{
						break;
					}
				}
			}
			done=false;
			break;
		}
	}
}
