#pragma config(Sensor, S1,     touch,          sensorTouch)
#pragma config(Sensor, S3,     colorPort,      sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x=0;
	for(x=1; x<60000; x=x+1){
		motor[motorB]=100;
		motor[motorC]=-100;
		wait1Msec(1);
		if(SensorValue(touch) == 1){
			motor[motorB]=0;
			motor[motorC]=0;
			while(true){
				nxtDisplayStringAt(30, 31, "%d",x);
			}
		}
	}
}
